org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Drobolectric.offline=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false
android.builtInKotlin=false
android.newDsl=false
android.dependency.useConstraints=false
ksp.useKSP2=false
