package com.sapisehat.app.report

import com.sapisehat.app.domain.model.DetectionResult
import com.sapisehat.app.domain.model.EarlyDetectionOutcome
import com.sapisehat.app.domain.model.LocationSource
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Builds the text content for a detection report.
 * Pure function — no Android dependencies, fully testable.
 */
object ReportContentBuilder {

    data class ReportContent(
        val title: String,
        val subtitle: String,
        val resultLines: List<String>,
        val scoreLines: List<String>,
        val metadataLines: List<String>,
        val disclaimerLines: List<String>,
    )

    fun build(result: DetectionResult, appVersionName: String): ReportContent {
        val locale = Locale.getDefault()
        val dateStr = SimpleDateFormat("dd MMM yyyy, HH:mm", locale).format(Date(result.timestamp))

        val resultLabel = if (result.outcome == EarlyDetectionOutcome.INSUFFICIENT_VISUAL_EVIDENCE) {
            "Insufficient visual evidence"
        } else {
            result.displayLabel
        }

        val resultLines = mutableListOf(
            "Date: $dateStr",
            "Early Indication: $resultLabel",
            "Confidence: ${(result.confidence * 100).toInt()}%",
            "Reliable: ${if (result.isReliable) "Yes" else "No"}",
            "Inference Mode: ${result.inferenceMode.name}",
        )

        if (result.outcome == EarlyDetectionOutcome.INSUFFICIENT_VISUAL_EVIDENCE) {
            resultLines.add("Action: Retake the photo with clear visible symptoms or ask an animal health advisor to review it.")
        }

        val scoreLines = result.allScores.entries
            .sortedByDescending { it.value }
            .map { (key, score) -> "$key: ${(score * 100).toInt()}%" }

        val metadataLines = mutableListOf<String>()
        result.appVersion?.let { metadataLines.add("App Version: $it") }
        result.modelVersion?.let { metadataLines.add("Model Version: $it") }
        result.preprocessingSummary?.let { metadataLines.add("Preprocessing: $it") }
        metadataLines.add("Consent Status: ${result.consentStatus.name}")
        if (result.latitude != null && result.longitude != null) {
            val sourceLabel = when (result.locationSource) {
                LocationSource.GPS -> "GPS"
                LocationSource.MANUAL -> "Manual"
                else -> ""
            }
            val locText = "%.2f, %.2f".format(result.latitude, result.longitude) +
                if (sourceLabel.isNotEmpty()) " ($sourceLabel)" else ""
            metadataLines.add("Coarse Location: $locText")
        }

        val disclaimerLines = listOf(
            "This report is an early detection indication from an AI model (MobileNetV2).",
            "It is NOT a veterinary diagnosis, certificate, or official document.",
            "Consult a professional veterinarian for confirmation and treatment.",
            "Generated by SapiSehat v$appVersionName",
        )

        return ReportContent(
            title = "SapiSehat — Early Detection Report",
            subtitle = "This is an early indication from an AI model, not a final diagnosis.",
            resultLines = resultLines,
            scoreLines = scoreLines,
            metadataLines = metadataLines,
            disclaimerLines = disclaimerLines,
        )
    }
}
